import { PatientRecord } from './types';

export const initialPatientsData: PatientRecord[] = [
  {
    id: 'BHC-P-000001',
    fullName: 'Rahul Sutar',
    dob: '1992-04-12',
    age: 34,
    gender: 'Male',
    country: 'India',
    city: 'Miraj',
    phone: '+91 95275 19903',
    whatsappNumber: '+91 95275 19903',
    email: 'sutarrahul61@gmail.com',
    address: 'Wanlesswadi, Sangli-Miraj Road',
    stateProvince: 'Maharashtra',
    postalCode: '416410',
    preferredLanguage: 'Marathi',
    passportNumber: 'Z8912341',
    status: 'In Consultation',
    treatmentRequired: 'Orthopaedics - Knee Assessment',
    primaryDiagnosis: 'Early degenerative changes right knee',
    assignedHospitalId: 'HOSP-001',
    assignedHospitalName: 'Wanless Hospital (Miraj Medical Centre)',
    assignedDoctorId: 'DOC-001',
    assignedDoctorName: 'Dr. Anand Patil',
    leadReferenceId: 'MSMT-716233',
    registeredDate: '2026-09-21',
    emergencyContact: {
      name: 'Family Member',
      relationship: 'Brother',
      phone: '+91 95275 19904',
    },
  },
  {
    id: 'BHC-P-000002',
    fullName: 'Rahim Al-Mansoor',
    dob: '1958-08-20',
    age: 68,
    gender: 'Male',
    country: 'United Arab Emirates',
    city: 'Dubai',
    phone: '+971 50 123 4567',
    whatsappNumber: '+971 50 123 4567',
    email: 'rahim.mansoor@example.com',
    address: 'Al Barsha 2, Villa 45',
    stateProvince: 'Dubai',
    postalCode: '00000',
    preferredLanguage: 'Arabic',
    passportNumber: 'N1948202',
    status: 'Scheduled for Surgery',
    treatmentRequired: 'Bilateral Robotic Total Knee Replacement',
    primaryDiagnosis: 'Severe Grade-IV Osteoarthritis bilateral knees',
    assignedHospitalId: 'HOSP-001',
    assignedHospitalName: 'Wanless Hospital (Miraj Medical Centre)',
    assignedDoctorId: 'DOC-001',
    assignedDoctorName: 'Dr. Anand Patil',
    leadReferenceId: 'LEAD-2026-001',
    registeredDate: '2026-09-18',
    emergencyContact: {
      name: 'Tariq Al-Mansoor',
      relationship: 'Son',
      phone: '+971 50 987 6543',
    },
  },
  {
    id: 'BHC-P-000003',
    fullName: 'Amina Khatun',
    dob: '1971-11-05',
    age: 54,
    gender: 'Female',
    country: 'Bangladesh',
    city: 'Dhaka',
    phone: '+880 171 987654',
    whatsappNumber: '+880 171 987654',
    email: 'amina.k@example.com',
    address: 'Dhanmondi Road 8/A',
    stateProvince: 'Dhaka',
    postalCode: '1209',
    preferredLanguage: 'Bengali',
    passportNumber: 'BK4928172',
    status: 'Under Evaluation',
    treatmentRequired: 'Coronary Angioplasty (PTCA)',
    primaryDiagnosis: 'Single vessel LAD 90% stenosis',
    assignedHospitalId: 'HOSP-002',
    assignedHospitalName: 'Sevasadan Lifeline Superspeciality Hospital',
    assignedDoctorId: 'DOC-002',
    assignedDoctorName: 'Dr. Rajesh Kulkarni',
    leadReferenceId: 'LEAD-2026-002',
    registeredDate: '2026-09-17',
    emergencyContact: {
      name: 'Kamal Hossain',
      relationship: 'Spouse',
      phone: '+880 171 112233',
    },
  },
];
